id: phs-dataset-pipeline
namespace: phs-dataset

inputs:
  - id: disease
    type: SELECT
    displayName: Select disease type
    values: [covid, respiratory]
    defaults: covid

variables:
  startDate: "{{trigger.previous | date('yyyyMMdd')}}"
  endDate: "{{trigger.date | date('yyyyMMdd')}}"
  queryCovid: "SELECT%20%2A%20from%20%22d304beee-badd-4d4d-b6cf-19651b303676%22%20WHERE%20%22WeekEnding%22%20%3E%3D%20{{render(vars.startDate)}}%20AND%20%22WeekEnding%22%20%3C%20{{render(vars.endDate)}}"
  queryResp: "SELECT%20%2A%20from%20%2275201270-269c-431b-9808-e52efe4c7b25%22%20WHERE%20%22WeekEnding%22%20%3E%3D%20{{render(vars.startDate)}}%20AND%20%22WeekEnding%22%20%3C%20{{render(vars.endDate)}}"
  jsonFile: "{{inputs.disease}}_{{vars.startDate}}_{{vars.endDate}}.json"
  csvFile: "{{inputs.disease}}_{{vars.startDate}}_{{vars.endDate}}.csv"
  gcs_path: "gs://{{kv('GCP_BUCKET_NAME')}}"

tasks:

  - id: ifCovid
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.disease == 'covid'}}"
    then:
      - id: extractCovid
        type: io.kestra.plugin.core.http.Download
        uri: https://www.opendata.nhs.scot/api/3/action/datastore_search_sql?sql={{render(vars.queryCovid)}}

      - id: upload_to_gs_raw_covid
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.extractCovid.uri }}"
        to: "{{render(vars.gcs_path)}}/raw/{{render(vars.jsonFile)}}"

      - id: jsonataCovid
        type: io.kestra.plugin.transform.jsonata.TransformItems
        from: "{{ outputs.extractCovid.uri }}"
        expression:
          result.records
        
      - id: resultCovid
        type: io.kestra.plugin.serdes.csv.IonToCsv
        from: "{{ outputs.jsonataCovid.uri }}"

      - id: upload_to_gs_covid
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.resultCovid.uri }}"
        to: "{{render(vars.gcs_path)}}/csv/{{render(vars.csvFile)}}"

  
  - id: ifResp
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.disease == 'respiratory'}}"
    then:
      - id: extractResp
        type: io.kestra.plugin.core.http.Download
        uri: https://www.opendata.nhs.scot/api/3/action/datastore_search_sql?sql={{render(vars.queryResp)}}

      - id: upload_to_gs_raw_resp
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.extractResp.uri }}"
        to: "{{render(vars.gcs_path)}}/raw/{{render(vars.jsonFile)}}"
      
      - id: jsonataResp
        type: io.kestra.plugin.transform.jsonata.TransformItems
        from: "{{ outputs.extractResp.uri }}"
        expression:
          result.records
        
      - id: resultResp
        type: io.kestra.plugin.serdes.csv.IonToCsv
        from: "{{ outputs.jsonataResp.uri }}"
  
      - id: upload_to_gs_resp
        type: io.kestra.plugin.gcp.gcs.Upload
        from: "{{ outputs.resultResp.uri }}"
        to: "{{render(vars.gcs_path)}}/csv/{{render(vars.csvFile)}}"
  
  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: This will remove output files. If you'd like to explore Kestra outputs, disable it.

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"


triggers:
  - id: covid_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 1 * * 1"
    inputs:
      disease: covid

  - id: respiratory_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 1 * * 1"
    inputs:
      disease: respiratory